Fix Bug: Unmount event listener
TypeError: can't access property "setAttribute", headerMainNavRef.current is null... in feedback details when resizing window...